# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_control_pb2 as agent__control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentControlServiceStub(object):
    """============================================================
    Agent Control Service - Agent 生命周期控制
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAgent = channel.unary_stream(
                '/ironclaw.AgentControlService/StartAgent',
                request_serializer=agent__control__pb2.AgentRequest.SerializeToString,
                response_deserializer=agent__control__pb2.AgentState.FromString,
                _registered_method=True)
        self.SubmitEvaluationResult = channel.unary_unary(
                '/ironclaw.AgentControlService/SubmitEvaluationResult',
                request_serializer=agent__control__pb2.EvaluationResultRequest.SerializeToString,
                response_deserializer=agent__control__pb2.EvaluationResultResponse.FromString,
                _registered_method=True)
        self.RequestShutdown = channel.unary_unary(
                '/ironclaw.AgentControlService/RequestShutdown',
                request_serializer=agent__control__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=agent__control__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ironclaw.AgentControlService/HealthCheck',
                request_serializer=agent__control__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__control__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AgentControlServiceServicer(object):
    """============================================================
    Agent Control Service - Agent 生命周期控制
    ============================================================

    """

    def StartAgent(self, request, context):
        """启动 Agent 并获取状态流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitEvaluationResult(self, request, context):
        """提交评估结果（外部评估器调用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestShutdown(self, request, context):
        """请求关闭容器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.StartAgent,
                    request_deserializer=agent__control__pb2.AgentRequest.FromString,
                    response_serializer=agent__control__pb2.AgentState.SerializeToString,
            ),
            'SubmitEvaluationResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvaluationResult,
                    request_deserializer=agent__control__pb2.EvaluationResultRequest.FromString,
                    response_serializer=agent__control__pb2.EvaluationResultResponse.SerializeToString,
            ),
            'RequestShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestShutdown,
                    request_deserializer=agent__control__pb2.ShutdownRequest.FromString,
                    response_serializer=agent__control__pb2.ShutdownResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__control__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__control__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ironclaw.AgentControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ironclaw.AgentControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentControlService(object):
    """============================================================
    Agent Control Service - Agent 生命周期控制
    ============================================================

    """

    @staticmethod
    def StartAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ironclaw.AgentControlService/StartAgent',
            agent__control__pb2.AgentRequest.SerializeToString,
            agent__control__pb2.AgentState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitEvaluationResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.AgentControlService/SubmitEvaluationResult',
            agent__control__pb2.EvaluationResultRequest.SerializeToString,
            agent__control__pb2.EvaluationResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.AgentControlService/RequestShutdown',
            agent__control__pb2.ShutdownRequest.SerializeToString,
            agent__control__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.AgentControlService/HealthCheck',
            agent__control__pb2.HealthCheckRequest.SerializeToString,
            agent__control__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
