# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import evaluator_pb2 as evaluator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in evaluator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EvaluatorServiceStub(object):
    """============================================================
    External Evaluator Service - 外部评估器服务
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateStream = channel.stream_stream(
                '/ironclaw.EvaluatorService/EvaluateStream',
                request_serializer=evaluator__pb2.EvaluatorEvent.SerializeToString,
                response_deserializer=evaluator__pb2.EvalResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/ironclaw.EvaluatorService/StreamLogs',
                request_serializer=evaluator__pb2.LogRequest.SerializeToString,
                response_deserializer=evaluator__pb2.LogEntry.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ironclaw.EvaluatorService/HealthCheck',
                request_serializer=evaluator__pb2.EvaluatorHealthRequest.SerializeToString,
                response_deserializer=evaluator__pb2.EvaluatorHealthResponse.FromString,
                _registered_method=True)


class EvaluatorServiceServicer(object):
    """============================================================
    External Evaluator Service - 外部评估器服务
    ============================================================

    """

    def EvaluateStream(self, request_iterator, context):
        """评估迭代：双向流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """日志流：客户端订阅日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EvaluateStream,
                    request_deserializer=evaluator__pb2.EvaluatorEvent.FromString,
                    response_serializer=evaluator__pb2.EvalResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=evaluator__pb2.LogRequest.FromString,
                    response_serializer=evaluator__pb2.LogEntry.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=evaluator__pb2.EvaluatorHealthRequest.FromString,
                    response_serializer=evaluator__pb2.EvaluatorHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ironclaw.EvaluatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ironclaw.EvaluatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EvaluatorService(object):
    """============================================================
    External Evaluator Service - 外部评估器服务
    ============================================================

    """

    @staticmethod
    def EvaluateStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ironclaw.EvaluatorService/EvaluateStream',
            evaluator__pb2.EvaluatorEvent.SerializeToString,
            evaluator__pb2.EvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ironclaw.EvaluatorService/StreamLogs',
            evaluator__pb2.LogRequest.SerializeToString,
            evaluator__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.EvaluatorService/HealthCheck',
            evaluator__pb2.EvaluatorHealthRequest.SerializeToString,
            evaluator__pb2.EvaluatorHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
