# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import security_pb2 as security__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in security_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecurityServiceStub(object):
    """安全检测服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectPromptInjection = channel.unary_unary(
                '/ironclaw.SecurityService/DetectPromptInjection',
                request_serializer=security__pb2.PromptInjectionRequest.SerializeToString,
                response_deserializer=security__pb2.PromptInjectionResponse.FromString,
                _registered_method=True)
        self.ScanSecrets = channel.unary_unary(
                '/ironclaw.SecurityService/ScanSecrets',
                request_serializer=security__pb2.SecretScanRequest.SerializeToString,
                response_deserializer=security__pb2.SecretScanResponse.FromString,
                _registered_method=True)
        self.DetectDangerousCode = channel.unary_unary(
                '/ironclaw.SecurityService/DetectDangerousCode',
                request_serializer=security__pb2.DangerousCodeRequest.SerializeToString,
                response_deserializer=security__pb2.DangerousCodeResponse.FromString,
                _registered_method=True)
        self.CheckFirewall = channel.unary_unary(
                '/ironclaw.SecurityService/CheckFirewall',
                request_serializer=security__pb2.FirewallRequest.SerializeToString,
                response_deserializer=security__pb2.FirewallResponse.FromString,
                _registered_method=True)
        self.BatchCheck = channel.unary_unary(
                '/ironclaw.SecurityService/BatchCheck',
                request_serializer=security__pb2.BatchCheckRequest.SerializeToString,
                response_deserializer=security__pb2.BatchCheckResponse.FromString,
                _registered_method=True)


class SecurityServiceServicer(object):
    """安全检测服务
    """

    def DetectPromptInjection(self, request, context):
        """提示注入检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanSecrets(self, request, context):
        """敏感信息扫描
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectDangerousCode(self, request, context):
        """危险代码检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFirewall(self, request, context):
        """防火墙检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCheck(self, request, context):
        """批量检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectPromptInjection': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPromptInjection,
                    request_deserializer=security__pb2.PromptInjectionRequest.FromString,
                    response_serializer=security__pb2.PromptInjectionResponse.SerializeToString,
            ),
            'ScanSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanSecrets,
                    request_deserializer=security__pb2.SecretScanRequest.FromString,
                    response_serializer=security__pb2.SecretScanResponse.SerializeToString,
            ),
            'DetectDangerousCode': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDangerousCode,
                    request_deserializer=security__pb2.DangerousCodeRequest.FromString,
                    response_serializer=security__pb2.DangerousCodeResponse.SerializeToString,
            ),
            'CheckFirewall': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFirewall,
                    request_deserializer=security__pb2.FirewallRequest.FromString,
                    response_serializer=security__pb2.FirewallResponse.SerializeToString,
            ),
            'BatchCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCheck,
                    request_deserializer=security__pb2.BatchCheckRequest.FromString,
                    response_serializer=security__pb2.BatchCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ironclaw.SecurityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ironclaw.SecurityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityService(object):
    """安全检测服务
    """

    @staticmethod
    def DetectPromptInjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.SecurityService/DetectPromptInjection',
            security__pb2.PromptInjectionRequest.SerializeToString,
            security__pb2.PromptInjectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.SecurityService/ScanSecrets',
            security__pb2.SecretScanRequest.SerializeToString,
            security__pb2.SecretScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectDangerousCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.SecurityService/DetectDangerousCode',
            security__pb2.DangerousCodeRequest.SerializeToString,
            security__pb2.DangerousCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckFirewall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.SecurityService/CheckFirewall',
            security__pb2.FirewallRequest.SerializeToString,
            security__pb2.FirewallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ironclaw.SecurityService/BatchCheck',
            security__pb2.BatchCheckRequest.SerializeToString,
            security__pb2.BatchCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
