"""
Model-Based Grader - LLM-as-Judge

基于 LLM rubric 的评判
支持:
- Rubric 打分
- 自然语言断言
- 成对比较

参考 Anthropic Model-Based Grader 设计
"""

import os
from typing import Any, Optional

from ..benchmark import GraderType, ModelGraderConfig
from .base import BaseGrader, GraderOutput


# Default rubric for code quality assessment
DEFAULT_CODE_QUALITY_RUBRIC = """
You are evaluating the quality of code generated by an AI agent.

Score each criterion from 0-10:

1. **Correctness** (0-10): Does the code solve the stated problem correctly?
   - 0-3: Code does not compile or has major functional errors
   - 4-6: Code partially solves the problem with some errors
   - 7-8: Code mostly correct with minor issues
   - 9-10: Code fully correct and handles edge cases

2. **Code Quality** (0-10): Is the code well-structured and readable?
   - 0-3: Poor structure, unreadable, no error handling
   - 4-6: Basic structure, some readability issues
   - 7-8: Good structure, clear naming, basic error handling
   - 9-10: Excellent structure, clean code, comprehensive error handling

3. **Security** (0-10): Does the code avoid security vulnerabilities?
   - 0-3: Contains critical security issues (injection, hardcoded secrets)
   - 4-6: Some security concerns
   - 7-8: Mostly secure with minor issues
   - 9-10: No security issues detected

4. **Testing** (0-10): Are there adequate tests?
   - 0-3: No tests
   - 4-6: Basic tests, incomplete coverage
   - 7-8: Good test coverage
   - 9-10: Comprehensive tests with edge cases

Final Score = (Correctness + CodeQuality + Security + Testing) / 4

Pass threshold: Final Score >= 7.0
"""


class ModelGrader(BaseGrader):
    """LLM-as-Judge Grader"""

    def __init__(self, config: GraderConfig):
        super().__init__(config)
        assert config.grader_type == GraderType.MODEL_BASED, "Must be MODEL_BASED"
        assert config.model_config is not None, "model_config is required"
        self.model_config: ModelGraderConfig = config.model_config

    async def grade(
        self,
        task_id: str,
        transcript: list[dict[str, Any]],
        outcome: dict[str, Any],
        context: dict[str, Any],
    ) -> GraderOutput:
        """执行 LLM 评判"""
        import time

        start = time.perf_counter()

        try:
            rubric = self._build_rubric(context)

            # 构建评判 prompt
            judge_prompt = self._build_judge_prompt(task_id, transcript, outcome, context, rubric)

            # 调用 LLM
            result = await self._call_judge_model(judge_prompt)
            elapsed_ms = (time.perf_counter() - start) * 1000

            return GraderOutput(
                grader_name=self.name,
                grader_type=GraderType.MODEL_BASED,
                passed=result["passed"],
                score=result["score"],
                details=result["reasoning"],
                raw_output=result.get("raw", ""),
                latency_ms=elapsed_ms,
            )

        except Exception as e:
            elapsed_ms = (time.perf_counter() - start) * 1000
            return GraderOutput(
                grader_name=self.name,
                grader_type=GraderType.MODEL_BASED,
                passed=False,
                score=0.0,
                details=f"ModelGrader error: {e}",
                error=str(e),
                latency_ms=elapsed_ms,
            )

    def _build_rubric(self, context: dict[str, Any]) -> str:
        """构建 rubric"""
        if self.model_config.rubric_content:
            return self.model_config.rubric_content

        rubric_path = self.model_config.rubric_path
        if rubric_path:
            try:
                with open(rubric_path, encoding="utf-8") as f:
                    return f.read()
            except OSError as e:
                logger.warning(f"Failed to read rubric file {rubric_path}: {e}")

        return DEFAULT_CODE_QUALITY_RUBRIC

    def _build_judge_prompt(
        self,
        task_id: str,
        transcript: list[dict[str, Any]],
        outcome: dict[str, Any],
        context: dict[str, Any],
        rubric: str,
    ) -> str:
        """构建评判 prompt"""
        task_desc = context.get("task_desc", "Unknown task")
        expected_output = context.get("expected_output", "Not specified")
        prompt_text = context.get("prompt", "Not available")

        # 提取关键 transcript 片段
        transcript_snippet = self._summarize_transcript(transcript, max_entries=20)

        # 提取最终输出
        final_output = self._extract_final_output(outcome)

        judge_prompt = f"""# Evaluation Task: {task_id}

## Task Description
{task_desc}

## Agent Input Prompt
{prompt_text}

## Expected Output
{expected_output}

## Agent Execution Transcript (truncated)
{transcript_snippet}

## Final Output
{final_output}

## Rubric
{rubric}

## Output Format
Return your evaluation in this exact format:
PASS: <true/false>
SCORE: <0.0-1.0>
REASONING: <brief explanation of your decision>
"""
        return judge_prompt

    def _summarize_transcript(self, transcript: list[dict[str, Any]], max_entries: int = 20) -> str:
        """总结 transcript 为可读片段"""
        if not transcript:
            return "(no transcript)"

        lines = []
        for i, entry in enumerate(transcript[:max_entries]):
            if isinstance(entry, dict):
                role = entry.get("role", "unknown")
                content = entry.get("content", "")
                tool_calls = entry.get("tool_calls", [])

                if tool_calls:
                    tool_names = [tc.get("name", "unknown") for tc in tool_calls]
                    lines.append(f"  [{i}] {role}: called {tool_names}")
                elif content:
                    snippet = str(content)[:200]
                    lines.append(f"  [{i}] {role}: {snippet}...")
                else:
                    lines.append(f"  [{i}] {role}: (empty)")

        if len(transcript) > max_entries:
            lines.append(f"  ... ({len(transcript) - max_entries} more entries)")

        return "\n".join(lines)

    def _extract_final_output(self, outcome: dict[str, Any]) -> str:
        """提取最终输出"""
        if not outcome:
            return "(no outcome)"

        # 尝试提取 result 字段
        result = outcome.get("result", "")
        if result:
            return str(result)[:1000]

        # 否则序列化整个 outcome
        import json

        try:
            return json.dumps(outcome, ensure_ascii=False, indent=2)[:1000]
        except Exception:
            return str(outcome)[:1000]

    async def _call_judge_model(self, prompt: str) -> dict[str, Any]:
        """调用评判模型"""
        # 获取 API key
        api_key = os.getenv("ANTHROPIC_API_KEY") or os.getenv("OPENAI_API_KEY")
        if not api_key:
            # Fallback: 使用简单的启发式评判
            return self._fallback_judge(prompt)

        # 尝试 Anthropic API
        try:
            return await self._call_anthropic(prompt)
        except Exception as e:
            logger.debug(f"Anthropic API failed, trying OpenAI: {e}")

        # 尝试 OpenAI API
        try:
            return await self._call_openai(prompt)
        except Exception as e:
            logger.debug(f"OpenAI API failed: {e}")

        return self._fallback_judge(prompt)

    async def _call_anthropic(self, prompt: str) -> dict[str, Any]:
        """调用 Anthropic API"""
        import json

        try:
            import anthropic

            client = anthropic.Anthropic()
            response = client.messages.create(
                model=self.model_config.judge_model or "claude-sonnet-4-7",
                max_tokens=1024,
                messages=[{"role": "user", "content": prompt}],
            )

            raw = response.content[0].text if response.content else ""
            return self._parse_judge_response(raw)

        except ImportError:
            raise RuntimeError("anthropic package not installed")

    async def _call_openai(self, prompt: str) -> dict[str, Any]:
        """调用 OpenAI API"""
        import json

        try:
            import openai

            client = openai.OpenAI()
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=1024,
            )

            raw = response.choices[0].message.content if response.choices else ""
            return self._parse_judge_response(raw)

        except ImportError:
            raise RuntimeError("openai package not installed")

    def _fallback_judge(self, prompt: str) -> dict[str, Any]:
        """当没有 API key 时的 fallback 评判"""
        # 简单的启发式检查
        prompt_lower = prompt.lower()

        if "security" in prompt_lower or "vulnerability" in prompt_lower:
            # 安全检查 - 检查是否有危险模式
            if any(danger in prompt_lower for danger in ["eval(", "exec(", "os.system"]):
                return {
                    "passed": False,
                    "score": 0.0,
                    "reasoning": "Fallback: detected dangerous patterns",
                    "raw": "",
                }

        return {
            "passed": True,
            "score": 0.7,
            "reasoning": "Fallback: no clear failure detected",
            "raw": "",
        }

    def _parse_judge_response(self, raw: str) -> dict[str, Any]:
        """解析 LLM 输出"""
        import re

        # 提取 PASS
        pass_match = re.search(r"PASS:\s*(true|false|True|False|1|0)", raw, re.IGNORECASE)
        passed = False
        if pass_match:
            val = pass_match.group(1).lower()
            passed = val in ("true", "1")

        # 提取 SCORE
        score_match = re.search(r"SCORE:\s*([\d.]+)", raw, re.IGNORECASE)
        score = 0.5
        if score_match:
            try:
                score = float(score_match.group(1))
                score = max(0.0, min(1.0, score / 10.0))  # 假设 LLM 返回 0-10
            except ValueError:
                pass

        # 如果 pass 但 score 低，校正
        if passed and score < 0.7:
            score = 0.7

        # 提取 REASONING
        reasoning_match = re.search(r"REASONING:\s*(.+?)(?:\n|$)", raw, re.IGNORECASE | re.DOTALL)
        reasoning = reasoning_match.group(1).strip() if reasoning_match else "No reasoning provided"

        return {
            "passed": passed,
            "score": score,
            "reasoning": reasoning[:500],
            "raw": raw[:2000],
        }
